version: "3.8"

services:
    aria2:
        image: redwid/aria2-ng
        ports:
            - 6080:80
            - 6800:6800
        volumes: 
            - ${SERVER_DOWNLOAD_DIR}:/data
        environment: 
            - RPC_SECRET=hello
        restart: unless-stopped

    transmission:
        build: ./transmission
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        volumes: 
            - ${SERVER_DOWNLOAD_DIR}:/downloads
        restart: unless-stopped