version: "3.8"

services:
    transmission:
        build: ./transmission
        container_name: transmission
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        # volumes: 
        #     - ./dwnl:/downloads
        restart: unless-stopped